spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: trungem
    password: trungem2002@
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: create
